apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8080
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: docker.io/eskhas/my-app:0.0.0 # {"$imagepolicy": "default:my-app"}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: swe304
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres123
      imagePullSecrets:
        - name: regcred
