apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-app
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/eskhas/my-app
  secretRef:
    name: my-app-github
