apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: default
spec:
  interval: 15m
  path: "./apps/my-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app
